Automated Testing (#14)
* create testing functions for functions in geo.js

- still needs to fix

* mocha and chai sucessfully compile

- error: 'latLonToTileCoords is not a function' (find out why this error occurs)
- somehow all tests are failing

* updated with es6 syntax

utilizedes6 syntax for geo and test.js and now need to figure out why some of the tests are wrong

* fixed test cases

* Add test automation; remove .DS_Store files;

* Add TurfJS to the global namespace when testing

---------

Co-authored-by: Daniel W. Steinbrook <dsteinbrook@gmail.com>